/**
 * Milníky epoch 0–3.
 *
 * `cost` je RELATIVNÍ obtížnost v rámci epochy (zhruba 1–10), ne absolutní
 * číslo. Absolutní cena vzniká vynásobením `EPOCH_COST_SCALE`. Důvod: mezi
 * epochami se mění počet let na tick o pět řádů, takže absolutní ceny by nešly
 * autorsky odhadnout. Takhle se vyvažuje 14 čísel místo 150.
 *
 * `affinity` je to, co dělá dějiny kauzálními — milník se skóruje podle toho,
 * jak odpovídá na aktuální tlaky. Po třech stoletích sucha se zavlažování
 * prosadí dřív než tavení mědi, a kronika to umí říct.
 */

import type { Milestone } from './types.js';

/** Převod relativní obtížnosti na jednotky poznání. Laděno sweepem. */
export const EPOCH_COST_SCALE: readonly number[] = [
  54, // 0 Úsvit
  0.31, // 1 Neolit
  1.43, // 2 Doba bronzová
  54, // 3 Doba železná
  0.6, // 4 Klasická éra
  0.75, // 5 Věk víry
  0.35, // 6 Věk objevů
  0.25, // 7 Osvícenství
  0.22, // 8 Průmysl
  0.18, // 9 Elektřina a atom
  0.14, // 10 Informace
  0.1, // 11 Sítě a biotechnologie
  0.12, // 12 Postlidská éra
  0.2, // 13 Transcendence
];

export const MILESTONES: readonly Milestone[] = [
  // ───────────────────────────── Epocha 0 — Úsvit
  {
    id: 'fire',
    name: 'Oheň',
    epoch: 0,
    blurb: 'První udržený plamen. Noc přestala být nepřítelem.',
    cost: 3,
    affinity: { cold: 0.9, hunger: 0.3, curiosity: 0.2 },
    unlocks: { capacity: 1.15, relief: { cold: 0.3 }, research: 1.1 },
    fragility: 0.02,
  },
  {
    id: 'stone_tools',
    name: 'Kamenné nástroje',
    epoch: 0,
    blurb: 'Otloukaný pazourek — první věc, která nevznikla sama.',
    cost: 3,
    needsResources: ['stone'],
    affinity: { hunger: 0.6, curiosity: 0.3 },
    unlocks: { capacity: 1.15, research: 1.1 },
    fragility: 0.02,
  },
  {
    id: 'language',
    name: 'Řeč',
    epoch: 0,
    blurb: 'Zvuk, který znamená něco, co tu není.',
    cost: 5,
    affinity: { curiosity: 0.8, hunger: 0.2 },
    unlocks: { research: 1.45, specialization: 0.05 },
    fragility: 0.01,
  },
  {
    id: 'cooking',
    name: 'Vaření',
    epoch: 0,
    blurb: 'Oheň jako první vnější žaludek.',
    requires: { all: ['fire'] },
    cost: 2,
    affinity: { hunger: 0.7, disease: 0.3 },
    unlocks: { capacity: 1.2, relief: { hunger: 0.15 } },
    fragility: 0.02,
  },
  {
    id: 'clothing',
    name: 'Oděv z kůží',
    epoch: 0,
    blurb: 'Cizí kožich na vlastních zádech.',
    requires: { all: ['stone_tools'] },
    needsResources: ['hide'],
    cost: 3,
    affinity: { cold: 0.95 },
    unlocks: { relief: { cold: 0.35 }, capacity: 1.1 },
    fragility: 0.03,
  },
  {
    id: 'shelter',
    name: 'Přístřešek',
    epoch: 0,
    blurb: 'Stavba tam, kde jeskyně nebyla.',
    requires: { all: ['stone_tools'] },
    needsResources: ['wood'],
    cost: 4,
    affinity: { cold: 0.7, crowding: 0.3 },
    unlocks: { capacity: 1.2, relief: { cold: 0.2 } },
    fragility: 0.04,
  },
  {
    id: 'spear',
    name: 'Oštěp',
    epoch: 0,
    blurb: 'Vzdálenost mezi lovcem a smrtí se prodloužila.',
    requires: { all: ['stone_tools'] },
    cost: 3,
    affinity: { hunger: 0.7, war: 0.5 },
    unlocks: { capacity: 1.15, might: 0.1 },
    fragility: 0.03,
  },
  {
    id: 'hunting_party',
    name: 'Organizovaný lov',
    epoch: 0,
    blurb: 'Deset lidí s plánem uloví to, co dvacet bez něj nikdy.',
    requires: { all: ['spear', 'language'] },
    cost: 5,
    affinity: { hunger: 0.9 },
    unlocks: { capacity: 1.3, specialization: 0.05 },
    fragility: 0.05,
  },
  {
    id: 'hide_working',
    name: 'Zpracování kůží',
    epoch: 0,
    blurb: 'Škrabka, šlacha, jehla z kosti.',
    requires: { all: ['clothing'] },
    needsResources: ['hide', 'flint'],
    cost: 3,
    affinity: { cold: 0.5 },
    unlocks: { relief: { cold: 0.15 }, specialization: 0.05 },
    fragility: 0.05,
  },
  {
    id: 'bow',
    name: 'Luk',
    epoch: 0,
    blurb: 'Uložená síla, vypuštěná v jediném okamžiku.',
    requires: { all: ['spear'] },
    needsResources: ['fiber', 'wood'],
    cost: 6,
    affinity: { hunger: 0.7, war: 0.7 },
    unlocks: { capacity: 1.2, might: 0.25 },
    fragility: 0.08,
  },
  {
    id: 'burial',
    name: 'Pohřbívání mrtvých',
    epoch: 0,
    blurb: 'První gesto, které nemá žádný praktický užitek.',
    requires: { all: ['language'] },
    cost: 4,
    affinity: { curiosity: 0.6, disease: 0.3 },
    unlocks: { relief: { disease: 0.1 }, research: 1.05 },
    fragility: 0.02,
  },
  {
    id: 'cave_art',
    name: 'Jeskynní malba',
    epoch: 0,
    blurb: 'Ruka obtažená okrem. Někdo tu byl.',
    requires: { all: ['language', 'fire'] },
    cost: 5,
    affinity: { curiosity: 1 },
    unlocks: { research: 1.2 },
    fragility: 0.06,
  },
  {
    id: 'raft',
    name: 'Vor',
    epoch: 0,
    blurb: 'Voda přestala být hranicí.',
    requires: { all: ['stone_tools'] },
    needsResources: ['wood'],
    cost: 5,
    costMods: [
      { why: 'na suchém světě není co splavovat', planet: { key: 'hydrology', below: 0.3 }, mul: 3 },
      { why: 'svět protkaný vodou', planet: { key: 'hydrology', above: 0.7 }, mul: 0.5 },
    ],
    affinity: { hunger: 0.4, crowding: 0.4, curiosity: 0.3 },
    unlocks: { capacity: 1.1 },
    fragility: 0.08,
  },
  {
    id: 'lunar_calendar',
    name: 'Měsíční kalendář',
    epoch: 0,
    blurb: 'Nebe jako první hodiny.',
    requires: { all: ['language'] },
    cost: 6,
    affinity: { curiosity: 0.8, hunger: 0.3 },
    unlocks: { research: 1.15, specialization: 0.05 },
    fragility: 0.12,
  },

  // ───────────────────────────── Epocha 1 — Neolit
  {
    id: 'agriculture',
    name: 'Zemědělství',
    epoch: 1,
    blurb: 'Zasít a čekat — nejradikálnější myšlenka v dějinách.',
    requires: { all: ['language'], any: ['hunting_party', 'cooking'] },
    cost: 8,
    costMods: [
      { why: 'skoupá vegetace', planet: { key: 'hydrology', below: 0.25 }, mul: 2 },
    ],
    affinity: { hunger: 1, crowding: 0.4 },
    unlocks: { capacity: 4, relief: { hunger: 0.3 }, specialization: 0.1 },
    fragility: 0.1,
  },
  {
    id: 'domestication',
    name: 'Domestikace zvířat',
    epoch: 1,
    blurb: 'Vlk u ohně, koza v ohradě.',
    requires: { all: ['hunting_party'] },
    cost: 6,
    costMods: [
      { why: 'chudá megafauna', planet: { key: 'oxygen', below: 0.16 }, mul: 1.6 },
    ],
    affinity: { hunger: 0.8, cold: 0.2 },
    unlocks: { capacity: 1.6, relief: { hunger: 0.15 } },
    fragility: 0.1,
  },
  {
    id: 'pottery',
    name: 'Hrnčířství',
    epoch: 1,
    blurb: 'Hlína, která si po ohni pamatuje tvar.',
    requires: { all: ['fire'] },
    needsResources: ['clay'],
    cost: 4,
    affinity: { hunger: 0.5, curiosity: 0.3 },
    unlocks: { capacity: 1.2, specialization: 0.05 },
    fragility: 0.12,
  },
  {
    id: 'weaving',
    name: 'Tkaní',
    epoch: 1,
    blurb: 'Z vlákna plocha.',
    requires: { all: ['hide_working'] },
    needsResources: ['fiber'],
    cost: 5,
    affinity: { cold: 0.6 },
    unlocks: { relief: { cold: 0.2 }, specialization: 0.05 },
    fragility: 0.12,
  },
  {
    id: 'settlement',
    name: 'Trvalá osada',
    epoch: 1,
    blurb: 'Poprvé se vyplatí stavět něco, co přežije stavitele.',
    requires: { all: ['agriculture'] },
    cost: 6,
    affinity: { crowding: 0.6, cold: 0.3 },
    unlocks: { capacity: 1.5, specialization: 0.15, research: 1.2 },
    fragility: 0.15,
  },
  {
    id: 'irrigation',
    name: 'Zavlažování',
    epoch: 1,
    blurb: 'Řeku lze přesvědčit, aby tekla jinudy.',
    requires: { all: ['agriculture', 'settlement'] },
    cost: 8,
    costMods: [
      { why: 'na vyprahlém světě je to otázka přežití', planet: { key: 'hydrology', below: 0.3 }, mul: 0.6 },
    ],
    affinity: { hunger: 1 },
    unlocks: { capacity: 1.9, relief: { hunger: 0.25 } },
    fragility: 0.2,
  },
  {
    id: 'granary',
    name: 'Sýpka',
    epoch: 1,
    blurb: 'Přebytek, který přečká zimu, změní všechno.',
    requires: { all: ['agriculture', 'pottery'] },
    cost: 5,
    affinity: { hunger: 0.9, cold: 0.2 },
    unlocks: { capacity: 1.35, relief: { hunger: 0.25 }, specialization: 0.1 },
    fragility: 0.18,
  },
  {
    id: 'herbal_medicine',
    name: 'Bylinné léčitelství',
    epoch: 1,
    blurb: 'Někdo si všiml, které listy pomáhají.',
    requires: { all: ['language'] },
    cost: 5,
    affinity: { disease: 1 },
    unlocks: { relief: { disease: 0.3 }, capacity: 1.15 },
    fragility: 0.15,
  },
  {
    id: 'trade',
    name: 'Směna',
    epoch: 1,
    blurb: 'Dvě tlupy zjistily, že se nemusí pobít.',
    requires: { all: ['settlement'] },
    cost: 5,
    affinity: { crowding: 0.3, hunger: 0.3, curiosity: 0.3 },
    unlocks: { research: 1.3, specialization: 0.1 },
    fragility: 0.2,
  },
  {
    id: 'chiefdom',
    name: 'Náčelnictví',
    epoch: 1,
    blurb: 'Někdo rozhoduje za ostatní. Zatím se to zdá praktické.',
    requires: { all: ['settlement'] },
    cost: 6,
    affinity: { war: 0.6, crowding: 0.5 },
    unlocks: { specialization: 0.15, might: 0.2 },
    fragility: 0.25,
  },
  {
    id: 'ancestor_cult',
    name: 'Kult předků',
    epoch: 1,
    blurb: 'Mrtví dostali hlas v poradách živých.',
    requires: { all: ['burial', 'settlement'] },
    cost: 5,
    affinity: { curiosity: 0.5, disease: 0.2, war: 0.2 },
    unlocks: { research: 1.1, specialization: 0.05 },
    fragility: 0.1,
  },
  {
    id: 'sailing',
    name: 'Plavba',
    epoch: 1,
    blurb: 'Plachta místo pádla.',
    requires: { all: ['raft', 'weaving'] },
    cost: 7,
    costMods: [
      { why: 'suchý svět nemá kam plout', planet: { key: 'hydrology', below: 0.3 }, mul: 4 },
      { why: 'vodnatý svět plavbu vynucuje', planet: { key: 'hydrology', above: 0.7 }, mul: 0.45 },
    ],
    affinity: { crowding: 0.5, hunger: 0.3, curiosity: 0.4 },
    unlocks: { capacity: 1.2, research: 1.1 },
    fragility: 0.2,
  },
  {
    id: 'megalith',
    name: 'Megality',
    epoch: 1,
    blurb: 'Kameny postavené proto, aby stály déle než kdokoli, kdo je viděl vztyčit.',
    requires: { all: ['chiefdom'] },
    needsResources: ['stone'],
    cost: 7,
    costMods: [
      { why: 'těžká gravitace', planet: { key: 'gravity', above: 1.3 }, mul: 2.2 },
      { why: 'lehká gravitace', planet: { key: 'gravity', below: 0.8 }, mul: 0.6 },
    ],
    affinity: { curiosity: 0.7 },
    unlocks: { research: 1.15, specialization: 0.1 },
    fragility: 0.05,
  },

  // ───────────────────────────── Epocha 2 — Doba bronzová
  {
    id: 'copper_smelting',
    name: 'Tavení mědi',
    epoch: 2,
    blurb: 'Kámen, který po ohni teče.',
    requires: { all: ['pottery'] },
    needsResources: ['copper'],
    cost: 6,
    affinity: { war: 0.4, curiosity: 0.5, hunger: 0.2 },
    unlocks: { capacity: 1.2, might: 0.2, specialization: 0.1 },
    fragility: 0.25,
  },
  {
    id: 'bronze',
    name: 'Bronz',
    epoch: 2,
    blurb: 'Dva měkké kovy dají jeden tvrdý.',
    requires: { all: ['copper_smelting'] },
    needsResources: ['tin'],
    cost: 7,
    costMods: [
      { why: 'cín se tu skoro nevyskytuje', ore: { id: 'tin', below: 0.3 }, mul: 6 },
    ],
    affinity: { war: 0.7, curiosity: 0.3 },
    unlocks: { might: 0.5, capacity: 1.15, specialization: 0.1 },
    fragility: 0.3,
  },
  {
    id: 'obsidian_blades',
    name: 'Obsidiánové čepele',
    epoch: 2,
    blurb: 'Sopečné sklo ostřejší než jakýkoli kov.',
    requires: { all: ['stone_tools'] },
    needsResources: ['obsidian'],
    cost: 4,
    affinity: { war: 0.8, hunger: 0.4 },
    unlocks: { might: 0.35, specialization: 0.05 },
    fragility: 0.15,
  },
  {
    id: 'ceramic_engineering',
    name: 'Keramické stavitelství',
    epoch: 2,
    blurb: 'Kde není kov, musí stačit vypálená hlína — a stačí překvapivě dobře.',
    requires: { all: ['pottery', 'settlement'] },
    needsResources: ['clay'],
    cost: 6,
    costMods: [
      { why: 'svět chudý na měď nemá jinou cestu', ore: { id: 'copper', below: 0.3 }, mul: 0.5 },
    ],
    affinity: { crowding: 0.5, cold: 0.3 },
    unlocks: { capacity: 1.35, specialization: 0.1, research: 1.1 },
    fragility: 0.2,
  },
  {
    id: 'writing',
    name: 'Písmo',
    epoch: 2,
    blurb: 'Paměť, která nezávisí na tom, kdo je naživu.',
    requires: { all: ['trade', 'chiefdom'] },
    cost: 8,
    affinity: { curiosity: 0.8, crowding: 0.3 },
    unlocks: { literacy: 0.25, research: 1.7, specialization: 0.1 },
    fragility: 0.35,
  },
  {
    id: 'plow',
    name: 'Pluh',
    epoch: 2,
    blurb: 'Zvíře táhne to, co dřív nesl člověk.',
    requires: { all: ['domestication'], any: ['copper_smelting', 'ceramic_engineering'] },
    cost: 6,
    affinity: { hunger: 0.9 },
    unlocks: { capacity: 1.7, relief: { hunger: 0.2 } },
    fragility: 0.2,
  },
  {
    id: 'wheel',
    name: 'Kolo',
    epoch: 2,
    blurb: 'Kruh, který ušetří víc práce než cokoli předtím.',
    requires: { all: ['settlement'] },
    needsResources: ['wood'],
    cost: 6,
    costMods: [
      { why: 'těžká gravitace drtí nápravy', planet: { key: 'gravity', above: 1.35 }, mul: 2.5 },
    ],
    affinity: { crowding: 0.4, hunger: 0.3 },
    unlocks: { capacity: 1.2, research: 1.1 },
    fragility: 0.15,
  },
  {
    id: 'city',
    name: 'Město',
    epoch: 2,
    blurb: 'Tolik lidí pohromadě, že se navzájem neznají.',
    requires: { all: ['granary', 'chiefdom'], any: ['irrigation', 'plow'] },
    cost: 8,
    affinity: { crowding: 0.8 },
    unlocks: { capacity: 1.6, specialization: 0.2, research: 1.3 },
    fragility: 0.4,
  },
  {
    id: 'arithmetic',
    name: 'Počty',
    epoch: 2,
    blurb: 'Kolik pytlů obilí komu patří.',
    requires: { all: ['writing'] },
    cost: 5,
    affinity: { curiosity: 0.7, crowding: 0.3 },
    unlocks: { research: 1.35, literacy: 0.1 },
    fragility: 0.35,
  },
  {
    id: 'astronomy',
    name: 'Hvězdářství',
    epoch: 2,
    blurb: 'Nebe je mechanismus a dá se předpovědět.',
    requires: { all: ['arithmetic', 'lunar_calendar'] },
    cost: 7,
    costMods: [
      { why: 'hustá atmosféra zakrývá hvězdy', planet: { key: 'atmosphereDensity', above: 1.6 }, mul: 2.5 },
    ],
    affinity: { curiosity: 1, hunger: 0.2 },
    unlocks: { research: 1.25 },
    fragility: 0.4,
  },
  {
    id: 'bronze_weapons',
    name: 'Bronzové zbraně',
    epoch: 2,
    blurb: 'Válka se stala řemeslem.',
    requires: { all: ['bronze'] },
    cost: 5,
    affinity: { war: 1 },
    unlocks: { might: 0.7 },
    fragility: 0.3,
  },
  {
    id: 'sail_ship',
    name: 'Plachetnice',
    epoch: 2,
    blurb: 'Loď, která nepotřebuje pobřeží na dohled.',
    requires: { all: ['sailing'], any: ['copper_smelting', 'ceramic_engineering'] },
    cost: 7,
    affinity: { crowding: 0.4, curiosity: 0.5 },
    unlocks: { capacity: 1.2, research: 1.15 },
    fragility: 0.3,
  },

  // ───────────────────────────── Epocha 3 — Doba železná
  {
    id: 'iron_smelting',
    name: 'Tavení železa',
    epoch: 3,
    blurb: 'Horší kov než bronz, ale je ho všude dost.',
    requires: { any: ['copper_smelting', 'ceramic_engineering'] },
    needsResources: ['iron'],
    cost: 7,
    costMods: [
      { why: 'železo je tu vzácné', ore: { id: 'iron', below: 0.3 }, mul: 5 },
    ],
    affinity: { war: 0.6, hunger: 0.3, curiosity: 0.3 },
    unlocks: { capacity: 1.25, might: 0.4, specialization: 0.1 },
    fragility: 0.3,
  },
  {
    id: 'iron_weapons',
    name: 'Železné zbraně',
    epoch: 3,
    blurb: 'Zbroj přestala být výsadou.',
    requires: { all: ['iron_smelting'] },
    cost: 5,
    affinity: { war: 1 },
    unlocks: { might: 0.9 },
    fragility: 0.3,
  },
  {
    id: 'iron_plow',
    name: 'Železný pluh',
    epoch: 3,
    blurb: 'Půda, která dosud odolávala, se poddala.',
    requires: { all: ['iron_smelting', 'plow'] },
    cost: 5,
    affinity: { hunger: 0.9 },
    unlocks: { capacity: 1.6, relief: { hunger: 0.2 } },
    fragility: 0.25,
  },
  {
    id: 'alphabet',
    name: 'Abeceda',
    epoch: 3,
    blurb: 'Třicet znaků místo tří tisíc. Psát může kdokoli.',
    requires: { all: ['writing'] },
    cost: 6,
    affinity: { curiosity: 0.8, crowding: 0.3 },
    unlocks: { literacy: 0.3, research: 1.5 },
    fragility: 0.35,
  },
  {
    id: 'coinage',
    name: 'Mince',
    epoch: 3,
    blurb: 'Hodnota se odpoutala od věci.',
    requires: { all: ['trade', 'arithmetic'], any: ['bronze', 'iron_smelting'] },
    needsResources: ['gold'],
    cost: 6,
    affinity: { crowding: 0.4, curiosity: 0.3 },
    unlocks: { research: 1.25, specialization: 0.15 },
    fragility: 0.4,
  },
  {
    id: 'roads',
    name: 'Cesty',
    epoch: 3,
    blurb: 'Vzdálenost se dá zkrátit, aniž by se zmenšila.',
    requires: { all: ['city', 'wheel'] },
    needsResources: ['stone'],
    cost: 6,
    affinity: { war: 0.4, crowding: 0.4 },
    unlocks: { research: 1.2, might: 0.2, capacity: 1.15 },
    fragility: 0.2,
  },
  {
    id: 'aqueduct',
    name: 'Vodovod',
    epoch: 3,
    blurb: 'Voda teče do města sama.',
    requires: { all: ['city', 'arithmetic'] },
    cost: 7,
    affinity: { disease: 0.9, crowding: 0.5, hunger: 0.3 },
    unlocks: { capacity: 1.4, relief: { disease: 0.3 } },
    fragility: 0.35,
  },
  {
    id: 'law_code',
    name: 'Zákoník',
    epoch: 3,
    blurb: 'Pravidla, která platí i na toho, kdo je vydal. Alespoň v teorii.',
    requires: { all: ['writing', 'city'] },
    cost: 6,
    affinity: { crowding: 0.6, war: 0.4 },
    unlocks: { specialization: 0.2, research: 1.15 },
    fragility: 0.4,
  },
  {
    id: 'standing_army',
    name: 'Stálé vojsko',
    epoch: 3,
    blurb: 'Vojáci, kteří nedělají nic jiného než vojáky.',
    requires: { all: ['law_code'], any: ['iron_weapons', 'bronze_weapons', 'obsidian_blades'] },
    cost: 7,
    affinity: { war: 1, crowding: 0.3 },
    unlocks: { might: 1, specialization: 0.1 },
    fragility: 0.45,
  },
  {
    id: 'geometry',
    name: 'Geometrie',
    epoch: 3,
    blurb: 'Tvrzení, které platí, i když ho nikdo neuvidí.',
    requires: { all: ['arithmetic', 'alphabet'] },
    cost: 7,
    affinity: { curiosity: 1 },
    unlocks: { research: 1.4, literacy: 0.1 },
    fragility: 0.45,
  },
  {
    id: 'philosophy',
    name: 'Filosofie',
    epoch: 3,
    blurb: 'Otázky, na které se nedá odpovědět prací.',
    requires: { all: ['alphabet', 'city'] },
    cost: 7,
    affinity: { curiosity: 1, crowding: 0.2 },
    unlocks: { research: 1.35, literacy: 0.15 },
    fragility: 0.5,
  },
  {
    id: 'crop_rotation',
    name: 'Střídání plodin',
    epoch: 3,
    blurb: 'Nechat pole odpočinout je také práce.',
    requires: { all: ['iron_plow'] },
    cost: 5,
    affinity: { hunger: 0.9 },
    unlocks: { capacity: 1.45, relief: { hunger: 0.2 } },
    fragility: 0.3,
  },
  {
    id: 'empire',
    name: 'Říše',
    epoch: 3,
    blurb: 'Tolik území, že okraj neví, co dělá střed.',
    requires: { all: ['standing_army', 'law_code', 'roads'] },
    cost: 9,
    affinity: { war: 0.7, crowding: 0.5 },
    unlocks: { capacity: 1.35, might: 0.5, research: 1.2, specialization: 0.15 },
    fragility: 0.6,
  },
];

/** Rychlý index podle id. */
export const MILESTONE_BY_ID: ReadonlyMap<string, Milestone> = new Map(
  MILESTONES.map((m) => [m.id, m]),
);

/** Milníky dané epochy. */
export function milestonesOfEpoch(epoch: number): Milestone[] {
  return MILESTONES.filter((m) => m.epoch === epoch);
}

/** Nejvyšší epocha, pro kterou jsou data. Dál se civilizace zatím nedostane. */
export const MAX_CONTENT_EPOCH = MILESTONES.reduce((max, m) => Math.max(max, m.epoch), 0);
