/**
 * Milníky epoch 4–13: od klasické éry po transcendenci.
 *
 * Vedle hlavní linie tu záměrně běží ALTERNATIVNÍ CESTY. Chybějící surovina
 * nemá civilizaci zastavit, ale odklonit:
 *
 *   energetika — pára (uhlí) │ vodní turbína (hydrologie) │ geotermál (vulkanismus)
 *   pohon      — spalovací motor (ropa) │ elektromotor (měď + dynamo)
 *   výpočty    — tranzistor (vzácné zeminy) │ reléový počítač (jen měď a přesná mechanika)
 *   vesmír     — chemická raketa │ hmotový urychlovač (nízká gravitace)
 *
 * Právě proto svět bez uhlí nedojde k průmyslu přes páru, ale přes vodu
 * a Voltův článek — a elektřinu objeví o staletí dřív, než ji známe my.
 * Nic z toho není naskriptované; plyne to z cen.
 */

import type { Milestone } from './types.js';

export const LATE_MILESTONES: readonly Milestone[] = [
  // ───────────────────────────── Epocha 4 — Klasická éra
  {
    id: 'library',
    name: 'Knihovna',
    epoch: 4,
    blurb: 'Vědění uložené mimo hlavy těch, kdo ho nasbírali.',
    requires: { all: ['alphabet', 'city'] },
    cost: 6,
    affinity: { curiosity: 0.9 },
    unlocks: { research: 1.5, literacy: 0.1 },
    fragility: 0.55,
  },
  {
    id: 'water_mill',
    name: 'Vodní mlýn',
    epoch: 4,
    blurb: 'První stroj, který pracuje, i když u něj nikdo nestojí.',
    requires: { all: ['wheel'] },
    cost: 6,
    costMods: [
      { why: 'na světě protkaném řekami', planet: { key: 'hydrology', above: 0.6 }, mul: 0.5 },
      { why: 'na suchém světě není co pohánět', planet: { key: 'hydrology', below: 0.3 }, mul: 4 },
    ],
    affinity: { hunger: 0.6, crowding: 0.3 },
    unlocks: { capacity: 1.35, research: 1.1, specialization: 0.1 },
    fragility: 0.3,
  },
  {
    id: 'concrete',
    name: 'Beton',
    epoch: 4,
    blurb: 'Kámen, který se dá nalít do jakéhokoli tvaru.',
    requires: { all: ['geometry', 'city'] },
    needsResources: ['stone'],
    cost: 6,
    affinity: { crowding: 0.6 },
    unlocks: { capacity: 1.4, specialization: 0.05 },
    fragility: 0.5,
  },
  {
    id: 'glassmaking',
    name: 'Sklářství',
    epoch: 4,
    blurb: 'Písek roztavený do průhlednosti.',
    requires: { all: ['pottery'], any: ['copper_smelting', 'ceramic_engineering'] },
    cost: 5,
    affinity: { curiosity: 0.5 },
    unlocks: { research: 1.15, specialization: 0.05 },
    fragility: 0.4,
  },
  {
    id: 'paper',
    name: 'Papír',
    epoch: 4,
    blurb: 'Levný povrch pro drahé myšlenky.',
    requires: { all: ['writing'], any: ['weaving', 'ceramic_engineering'] },
    cost: 5,
    affinity: { curiosity: 0.6 },
    unlocks: { literacy: 0.15, research: 1.3 },
    fragility: 0.4,
  },
  {
    id: 'medicine_school',
    name: 'Lékařská škola',
    epoch: 4,
    blurb: 'Léčení přestalo být tajemstvím jednotlivce.',
    requires: { all: ['herbal_medicine'], any: ['philosophy', 'library'] },
    cost: 6,
    affinity: { disease: 1 },
    unlocks: { relief: { disease: 0.25 }, capacity: 1.2, specialization: 0.1 },
    fragility: 0.5,
  },
  {
    id: 'sanitation',
    name: 'Kanalizace',
    epoch: 4,
    blurb: 'Město poprvé odvádí to, co vyrobí.',
    requires: { all: ['aqueduct'] },
    cost: 6,
    affinity: { disease: 0.9, crowding: 0.6 },
    unlocks: { capacity: 1.35, relief: { disease: 0.25 } },
    fragility: 0.5,
  },
  {
    id: 'siege_engines',
    name: 'Obléhací stroje',
    epoch: 4,
    blurb: 'Hradby přestaly stačit.',
    requires: { all: ['geometry'], any: ['iron_weapons', 'bronze_weapons'] },
    cost: 5,
    affinity: { war: 1 },
    unlocks: { might: 0.8 },
    fragility: 0.45,
  },
  {
    id: 'cartography',
    name: 'Mapy',
    epoch: 4,
    blurb: 'Svět zmenšený tak, aby se vešel na stůl.',
    requires: { all: ['geometry'], any: ['sail_ship', 'roads'] },
    cost: 5,
    affinity: { curiosity: 0.7, crowding: 0.3 },
    unlocks: { research: 1.2, capacity: 1.1 },
    fragility: 0.45,
  },
  {
    id: 'solar_calendar',
    name: 'Sluneční kalendář',
    epoch: 4,
    blurb: 'Rok rozdělený tak přesně, že se dá plánovat setba.',
    requires: { all: ['astronomy', 'arithmetic'] },
    cost: 5,
    affinity: { hunger: 0.5, curiosity: 0.6 },
    unlocks: { capacity: 1.15, research: 1.1 },
    fragility: 0.4,
  },
  {
    id: 'republic',
    name: 'Republika',
    epoch: 4,
    blurb: 'Moc, která se má vracet tam, odkud přišla.',
    requires: { all: ['law_code'], any: ['philosophy', 'library'] },
    cost: 7,
    affinity: { crowding: 0.5, war: 0.3 },
    unlocks: { specialization: 0.15, research: 1.2 },
    fragility: 0.6,
  },
  {
    id: 'surgery',
    name: 'Chirurgie',
    epoch: 4,
    blurb: 'Řezat, aby se uzdravil — velmi nesamozřejmá myšlenka.',
    requires: { all: ['medicine_school'], any: ['iron_smelting', 'obsidian_blades'] },
    cost: 6,
    affinity: { disease: 0.8, war: 0.4 },
    unlocks: { relief: { disease: 0.15 }, capacity: 1.1 },
    fragility: 0.55,
  },

  // ───────────────────────────── Epocha 5 — Věk víry
  {
    id: 'organized_religion',
    name: 'Organizované náboženství',
    epoch: 5,
    blurb: 'Víra dostala úřad, budovu a rozpočet.',
    requires: { all: ['ancestor_cult', 'writing'] },
    cost: 6,
    affinity: { disease: 0.4, war: 0.4, curiosity: 0.3 },
    unlocks: { specialization: 0.15, research: 1.1 },
    fragility: 0.25,
  },
  {
    id: 'monastery',
    name: 'Klášter',
    epoch: 5,
    blurb: 'Místo, kde se opisuje i to, čemu už nikdo nerozumí.',
    requires: { all: ['organized_religion'], any: ['library', 'paper'] },
    cost: 6,
    affinity: { curiosity: 0.7 },
    // Klášter je pojistka proti temnu — proto má sám nízkou křehkost.
    unlocks: { research: 1.25, literacy: 0.1 },
    fragility: 0.2,
  },
  {
    id: 'university',
    name: 'Univerzita',
    epoch: 5,
    blurb: 'Poprvé se platí za to, že někdo přemýšlí.',
    requires: { all: ['philosophy'], any: ['monastery', 'library'] },
    cost: 8,
    affinity: { curiosity: 1 },
    unlocks: { research: 1.6, literacy: 0.2, specialization: 0.1 },
    fragility: 0.5,
  },
  {
    id: 'alchemy',
    name: 'Alchymie',
    epoch: 5,
    blurb: 'Špatná teorie, výborná praxe.',
    requires: { all: ['glassmaking'], any: ['philosophy', 'monastery'] },
    cost: 6,
    affinity: { curiosity: 0.9, disease: 0.3 },
    unlocks: { research: 1.3 },
    fragility: 0.5,
  },
  {
    id: 'steel',
    name: 'Ocel',
    epoch: 5,
    blurb: 'Železo, kterému se přidalo přesně tolik uhlíku, kolik bylo třeba.',
    requires: { all: ['iron_smelting'] },
    cost: 7,
    costMods: [{ why: 'bez uhlí se výheň nedá uhlídat', ore: { id: 'coal', below: 0.3 }, mul: 2.5 }],
    affinity: { war: 0.7, curiosity: 0.3 },
    unlocks: { might: 0.6, capacity: 1.2, specialization: 0.1 },
    fragility: 0.45,
  },
  {
    id: 'heavy_plow',
    name: 'Těžký pluh',
    epoch: 5,
    blurb: 'Konečně se dá orat i těžká severní půda.',
    requires: { all: ['iron_plow'], any: ['steel', 'domestication'] },
    cost: 5,
    affinity: { hunger: 0.9, cold: 0.3 },
    unlocks: { capacity: 1.5, relief: { hunger: 0.2 } },
    fragility: 0.3,
  },
  {
    id: 'windmill',
    name: 'Větrný mlýn',
    epoch: 5,
    blurb: 'Vítr zapřažený tam, kde neteče žádná řeka.',
    requires: { any: ['water_mill', 'wheel'] },
    cost: 6,
    costMods: [
      { why: 'hustý vzduch tlačí do plachet víc', planet: { key: 'atmosphereDensity', above: 1.4 }, mul: 0.55 },
      { why: 'v řídkém vzduchu vítr neunese ani lopatky', planet: { key: 'atmosphereDensity', below: 0.6 }, mul: 3 },
    ],
    affinity: { hunger: 0.6, crowding: 0.3 },
    unlocks: { capacity: 1.3, specialization: 0.05 },
    fragility: 0.3,
  },
  {
    id: 'compass',
    name: 'Kompas',
    epoch: 5,
    blurb: 'Sever se dá najít i pod zataženou oblohou.',
    requires: { all: ['iron_smelting'], any: ['alchemy', 'astronomy'] },
    cost: 5,
    costMods: [
      { why: 'slabé magnetické pole střelku neudrží', planet: { key: 'magneticField', below: 0.25 }, mul: 5 },
    ],
    affinity: { curiosity: 0.6, crowding: 0.3 },
    unlocks: { research: 1.1 },
    fragility: 0.45,
  },
  {
    id: 'banking',
    name: 'Bankovnictví',
    epoch: 5,
    blurb: 'Peníze, které pracují, aniž by se hnuly z místa.',
    requires: { all: ['coinage'], any: ['paper', 'writing'] },
    cost: 6,
    affinity: { crowding: 0.4, curiosity: 0.3 },
    unlocks: { research: 1.25, specialization: 0.15 },
    fragility: 0.6,
  },
  {
    id: 'gunpowder',
    name: 'Střelný prach',
    epoch: 5,
    blurb: 'Alchymisté hledali nesmrtelnost a našli pravý opak.',
    requires: { all: ['alchemy'] },
    cost: 7,
    affinity: { war: 1, curiosity: 0.3 },
    unlocks: { might: 0.7 },
    fragility: 0.5,
  },
  {
    id: 'cathedral',
    name: 'Katedrála',
    epoch: 5,
    blurb: 'Stavba, kterou nikdo z těch, kdo ji začali, neuvidí hotovou.',
    requires: { all: ['organized_religion'], any: ['concrete', 'megalith'] },
    cost: 7,
    costMods: [{ why: 'těžká gravitace klenbu neunese', planet: { key: 'gravity', above: 1.35 }, mul: 2.5 }],
    affinity: { curiosity: 0.6 },
    unlocks: { research: 1.15, specialization: 0.1 },
    fragility: 0.35,
  },

  // ───────────────────────────── Epocha 6 — Věk objevů
  {
    id: 'printing_press',
    name: 'Knihtisk',
    epoch: 6,
    blurb: 'Myšlenka se poprvé šíří rychleji, než ji stačí někdo zakázat.',
    requires: { all: ['paper'], any: ['steel', 'bronze', 'iron_smelting', 'ceramic_engineering'] },
    cost: 8,
    affinity: { curiosity: 1 },
    unlocks: { literacy: 0.3, research: 1.8 },
    fragility: 0.4,
  },
  {
    id: 'optics',
    name: 'Optika',
    epoch: 6,
    blurb: 'Sklo, které ohýbá světlo přesně tak, jak chceme.',
    requires: { all: ['glassmaking'], any: ['geometry', 'university'] },
    cost: 6,
    affinity: { curiosity: 0.9 },
    unlocks: { research: 1.3 },
    fragility: 0.5,
  },
  {
    id: 'telescope',
    name: 'Dalekohled',
    epoch: 6,
    blurb: 'Obloha se ukázala být mnohem plnější, než se zdálo.',
    requires: { all: ['optics', 'astronomy'] },
    cost: 6,
    costMods: [
      { why: 'hustá atmosféra hvězdy rozmazává', planet: { key: 'atmosphereDensity', above: 1.5 }, mul: 3 },
      { why: 'průzračně řídký vzduch', planet: { key: 'atmosphereDensity', below: 0.7 }, mul: 0.6 },
    ],
    affinity: { curiosity: 1 },
    unlocks: { research: 1.35 },
    fragility: 0.55,
  },
  {
    id: 'ocean_ship',
    name: 'Zaoceánská loď',
    epoch: 6,
    blurb: 'Loď, která vydrží déle, než trvá cesta bez pevniny.',
    requires: { all: ['sail_ship'], any: ['compass', 'cartography'] },
    cost: 7,
    costMods: [{ why: 'na suchém světě není kam plout', planet: { key: 'hydrology', below: 0.3 }, mul: 5 }],
    affinity: { curiosity: 0.7, crowding: 0.5 },
    unlocks: { capacity: 1.3, research: 1.2 },
    fragility: 0.45,
  },
  {
    id: 'firearms',
    name: 'Palné zbraně',
    epoch: 6,
    blurb: 'Rok výcviku nahrazen týdnem.',
    requires: { all: ['gunpowder'], any: ['steel', 'iron_smelting', 'bronze'] },
    cost: 6,
    affinity: { war: 1 },
    unlocks: { might: 1.2 },
    fragility: 0.45,
  },
  {
    id: 'scientific_method',
    name: 'Vědecká metoda',
    epoch: 6,
    blurb: 'Pravidlo, že se člověk může mýlit — a jak to zjistit.',
    requires: { all: ['university'], any: ['printing_press', 'telescope'] },
    cost: 9,
    affinity: { curiosity: 1 },
    unlocks: { research: 2, literacy: 0.15 },
    fragility: 0.5,
  },
  {
    id: 'global_trade',
    name: 'Světový obchod',
    epoch: 6,
    blurb: 'Poprvé je levnější dovézt to než vypěstovat.',
    requires: { all: ['ocean_ship', 'banking'] },
    cost: 7,
    affinity: { crowding: 0.5, hunger: 0.4 },
    unlocks: { capacity: 1.35, research: 1.2, specialization: 0.1 },
    fragility: 0.6,
  },
  {
    id: 'new_crops',
    name: 'Nové plodiny',
    epoch: 6,
    blurb: 'Rostliny z druhého konce světa uživí víc lidí než ty domácí.',
    requires: { any: ['global_trade', 'ocean_ship'] },
    cost: 5,
    affinity: { hunger: 1 },
    unlocks: { capacity: 1.6, relief: { hunger: 0.2 } },
    fragility: 0.3,
  },
  {
    id: 'anatomy',
    name: 'Anatomie',
    epoch: 6,
    blurb: 'Tělo popsané zevnitř, ne podle toho, co se o něm říká.',
    requires: { all: ['surgery'], any: ['printing_press', 'scientific_method'] },
    cost: 6,
    affinity: { disease: 0.9 },
    unlocks: { relief: { disease: 0.2 }, research: 1.15 },
    fragility: 0.5,
  },
  {
    id: 'clockwork',
    name: 'Hodinový stroj',
    epoch: 6,
    blurb: 'Přesnost, kterou lze vyrobit a opakovat.',
    // Ozubená kola nemusí být ocelová — antikythérský mechanismus byl bronzový.
    requires: { all: ['geometry'], any: ['steel', 'bronze', 'ceramic_engineering'] },
    cost: 7,
    affinity: { curiosity: 0.7, crowding: 0.3 },
    unlocks: { research: 1.3, specialization: 0.15 },
    fragility: 0.5,
  },
  {
    id: 'accounting',
    name: 'Podvojné účetnictví',
    epoch: 6,
    blurb: 'Nudný vynález, který umožnil všechny ostatní.',
    requires: { all: ['banking', 'arithmetic'] },
    cost: 5,
    affinity: { crowding: 0.4 },
    unlocks: { research: 1.2, specialization: 0.15 },
    fragility: 0.55,
  },

  // ───────────────────────────── Epocha 7 — Osvícenství
  {
    id: 'calculus',
    name: 'Kalkulus',
    epoch: 7,
    blurb: 'Jazyk, ve kterém se dá zapsat pohyb.',
    requires: { all: ['scientific_method', 'geometry'] },
    cost: 7,
    affinity: { curiosity: 1 },
    unlocks: { research: 1.6, literacy: 0.1 },
    fragility: 0.55,
  },
  {
    id: 'chemistry',
    name: 'Chemie',
    epoch: 7,
    blurb: 'Alchymie, která se konečně přiznala, co neví.',
    requires: { all: ['alchemy', 'scientific_method'] },
    cost: 7,
    affinity: { curiosity: 0.9, disease: 0.4 },
    unlocks: { research: 1.45 },
    fragility: 0.55,
  },
  {
    id: 'precision_machining',
    name: 'Přesné obrábění',
    epoch: 7,
    blurb: 'Součástky, které do sebe padnou, i když je dělal někdo jiný.',
    requires: { all: ['clockwork'], any: ['steel', 'bronze', 'ceramic_engineering'] },
    cost: 7,
    affinity: { crowding: 0.4, war: 0.3 },
    unlocks: { research: 1.3, specialization: 0.15, might: 0.3 },
    fragility: 0.5,
  },
  {
    id: 'steam_engine',
    name: 'Parní stroj',
    epoch: 7,
    blurb: 'Oheň, který tlačí.',
    requires: { all: ['precision_machining'], any: ['chemistry', 'clockwork'] },
    needsResources: ['coal'],
    cost: 8,
    costMods: [
      { why: 'uhlí se tu skoro nevyskytuje', ore: { id: 'coal', below: 0.3 }, mul: 6 },
      { why: 'sloje na dosah ruky', ore: { id: 'coal', above: 1.4 }, mul: 0.65 },
    ],
    affinity: { crowding: 0.5, hunger: 0.3 },
    unlocks: { capacity: 1.5, research: 1.3, specialization: 0.1 },
    fragility: 0.5,
  },
  {
    id: 'water_turbine',
    name: 'Vodní turbína',
    epoch: 7,
    blurb: 'Řeka, ze které se dá vytáhnout mnohem víc než z mlýnského kola.',
    requires: { all: ['water_mill', 'precision_machining'] },
    cost: 7,
    costMods: [
      { why: 'kde není uhlí, zbývá voda', ore: { id: 'coal', below: 0.3 }, mul: 0.5 },
      { why: 'svět bohatý na spádové řeky', planet: { key: 'hydrology', above: 0.6 }, mul: 0.65 },
      { why: 'suchý svět nemá dost spádu', planet: { key: 'hydrology', below: 0.3 }, mul: 3.5 },
    ],
    affinity: { crowding: 0.5, hunger: 0.3 },
    unlocks: { capacity: 1.45, research: 1.25, specialization: 0.1 },
    fragility: 0.45,
  },
  {
    id: 'geothermal',
    name: 'Geotermální teplo',
    epoch: 7,
    blurb: 'Kotel, který nikdo nemusí přikládat.',
    requires: { all: ['precision_machining'] },
    cost: 8,
    costMods: [
      { why: 'na neklidné kůře stačí kopat', planet: { key: 'volcanism', above: 0.65 }, mul: 0.4 },
      { why: 'ke klidnému nitru se nedá dostat', planet: { key: 'volcanism', below: 0.35 }, mul: 6 },
    ],
    affinity: { cold: 0.6, crowding: 0.4 },
    unlocks: { capacity: 1.4, research: 1.2 },
    fragility: 0.45,
  },
  {
    id: 'voltaic_pile',
    name: 'Voltův článek',
    epoch: 7,
    blurb: 'Elektřina, která teče pořád — ne jen když zapraská.',
    requires: { all: ['chemistry'], any: ['copper_smelting', 'precision_machining'] },
    cost: 7,
    costMods: [
      { why: 'měď je tu všude', ore: { id: 'copper', above: 1.3 }, mul: 0.6 },
      { why: 'bez mědi se článek staví těžko', ore: { id: 'copper', below: 0.3 }, mul: 3.5 },
    ],
    affinity: { curiosity: 1 },
    unlocks: { research: 1.4 },
    fragility: 0.6,
  },
  {
    id: 'vaccination',
    name: 'Očkování',
    epoch: 7,
    blurb: 'Nemoc použitá proti sobě samé.',
    requires: { all: ['anatomy'], any: ['chemistry', 'scientific_method'] },
    cost: 7,
    affinity: { disease: 1 },
    unlocks: { relief: { disease: 0.35 }, capacity: 1.3 },
    fragility: 0.5,
  },
  {
    id: 'encyclopedia',
    name: 'Encyklopedie',
    epoch: 7,
    blurb: 'Pokus sepsat všechno, dokud to ještě jde.',
    requires: { all: ['printing_press', 'scientific_method'] },
    cost: 6,
    affinity: { curiosity: 1 },
    unlocks: { literacy: 0.2, research: 1.35 },
    fragility: 0.35,
  },
  {
    id: 'constitution',
    name: 'Ústava',
    epoch: 7,
    blurb: 'Pravidla, která se smí měnit jen podle pravidel.',
    requires: { all: ['encyclopedia'], any: ['republic', 'law_code'] },
    cost: 7,
    affinity: { war: 0.5, crowding: 0.5 },
    unlocks: { specialization: 0.2, research: 1.2 },
    fragility: 0.6,
  },
  {
    id: 'thermodynamics',
    name: 'Termodynamika',
    epoch: 7,
    blurb: 'Zjištění, že něco se nedá získat zadarmo. Nikdy.',
    requires: { all: ['calculus'], any: ['steam_engine', 'water_turbine', 'geothermal'] },
    cost: 7,
    affinity: { curiosity: 0.9 },
    unlocks: { research: 1.45 },
    fragility: 0.55,
  },
  {
    id: 'crop_science',
    name: 'Šlechtění plodin',
    epoch: 7,
    blurb: 'Výběr, který dřív trval tisíciletí, zvládnut za desetiletí.',
    requires: { all: ['scientific_method'], any: ['new_crops', 'crop_rotation'] },
    cost: 6,
    affinity: { hunger: 1 },
    unlocks: { capacity: 1.55, relief: { hunger: 0.2 } },
    fragility: 0.4,
  },

  // ───────────────────────────── Epocha 8 — Průmysl
  {
    id: 'factory',
    name: 'Továrna',
    epoch: 8,
    blurb: 'Práce rozdělená tak, že jí nikdo nerozumí celé.',
    requires: {
      all: ['precision_machining'],
      any: ['steam_engine', 'water_turbine', 'geothermal', 'windmill'],
    },
    cost: 8,
    affinity: { crowding: 0.7, hunger: 0.3 },
    unlocks: { capacity: 1.6, specialization: 0.2, research: 1.3 },
    fragility: 0.55,
  },
  {
    id: 'mass_steel',
    name: 'Hromadná ocel',
    epoch: 8,
    blurb: 'Ocel přestala být drahá a začala být samozřejmá.',
    requires: { all: ['factory', 'steel'] },
    cost: 6,
    costMods: [{ why: 'chudé sloje i rudy', ore: { id: 'iron', below: 0.4 }, mul: 3 }],
    affinity: { crowding: 0.5, war: 0.4 },
    unlocks: { capacity: 1.3, might: 0.5, specialization: 0.1 },
    fragility: 0.5,
  },
  {
    id: 'railway',
    name: 'Železnice',
    epoch: 8,
    blurb: 'Vzdálenost přestala být otázkou dnů.',
    requires: { all: ['mass_steel'], any: ['steam_engine', 'electric_generator'] },
    cost: 7,
    affinity: { crowding: 0.6, hunger: 0.3 },
    unlocks: { capacity: 1.4, research: 1.25, might: 0.3 },
    fragility: 0.55,
  },
  {
    id: 'electric_generator',
    name: 'Dynamo',
    epoch: 8,
    blurb: 'Pohyb převedený na proud a proud zpátky na pohyb.',
    requires: { all: ['voltaic_pile'], any: ['thermodynamics', 'water_turbine', 'steam_engine', 'geothermal'] },
    cost: 7,
    costMods: [{ why: 'bez mědi se vinutí nenamotá', ore: { id: 'copper', below: 0.3 }, mul: 3 }],
    affinity: { crowding: 0.5, curiosity: 0.5 },
    unlocks: { capacity: 1.4, research: 1.4, specialization: 0.1 },
    fragility: 0.6,
  },
  {
    id: 'telegraph',
    name: 'Telegraf',
    epoch: 8,
    blurb: 'Zpráva poprvé předběhla posla.',
    requires: { any: ['voltaic_pile', 'electric_generator'] },
    cost: 6,
    affinity: { crowding: 0.5, war: 0.4, curiosity: 0.5 },
    unlocks: { research: 1.4, might: 0.2 },
    fragility: 0.65,
  },
  {
    id: 'internal_combustion',
    name: 'Spalovací motor',
    epoch: 8,
    blurb: 'Výbuch zavřený do válce a opakovaný tisíckrát za minutu.',
    requires: { all: ['thermodynamics', 'precision_machining'] },
    needsResources: ['oil'],
    cost: 8,
    costMods: [{ why: 'ropa se tu prakticky nevyskytuje', ore: { id: 'oil', below: 0.3 }, mul: 5 }],
    affinity: { crowding: 0.4, war: 0.4 },
    unlocks: { capacity: 1.35, might: 0.4, research: 1.15 },
    fragility: 0.6,
  },
  {
    id: 'germ_theory',
    name: 'Teorie nákazy',
    epoch: 8,
    blurb: 'Nemoc má příčinu a ta příčina je živá.',
    requires: { all: ['optics'], any: ['vaccination', 'anatomy'] },
    cost: 7,
    affinity: { disease: 1 },
    unlocks: { relief: { disease: 0.4 }, capacity: 1.35 },
    fragility: 0.5,
  },
  {
    id: 'fertilizer',
    name: 'Umělá hnojiva',
    epoch: 8,
    blurb: 'Dusík vytažený ze vzduchu. Pole přestala být limitem.',
    requires: { all: ['chemistry', 'factory'] },
    cost: 7,
    affinity: { hunger: 1 },
    unlocks: { capacity: 1.7, relief: { hunger: 0.3 } },
    fragility: 0.55,
  },
  {
    id: 'public_health',
    name: 'Veřejné zdravotnictví',
    epoch: 8,
    blurb: 'Zdraví jako věc veřejná, ne soukromé štěstí.',
    requires: { all: ['germ_theory'], any: ['sanitation', 'constitution'] },
    cost: 6,
    affinity: { disease: 0.9, crowding: 0.5 },
    unlocks: { capacity: 1.35, relief: { disease: 0.3 } },
    fragility: 0.5,
  },
  {
    id: 'labor_movement',
    name: 'Dělnické hnutí',
    epoch: 8,
    blurb: 'Ti, kdo stroje obsluhují, zjistili, že jich je víc.',
    requires: { all: ['factory'], any: ['constitution', 'printing_press'] },
    cost: 6,
    affinity: { crowding: 0.8, war: 0.4 },
    unlocks: { specialization: 0.15, research: 1.15 },
    fragility: 0.55,
  },
  {
    id: 'assembly_line',
    name: 'Pásová výroba',
    epoch: 8,
    blurb: 'Výrobek jde k dělníkovi, ne dělník k výrobku.',
    requires: { all: ['factory'], any: ['internal_combustion', 'electric_generator'] },
    cost: 6,
    affinity: { crowding: 0.5 },
    unlocks: { capacity: 1.45, specialization: 0.15 },
    fragility: 0.55,
  },
  {
    id: 'photography',
    name: 'Fotografie',
    epoch: 8,
    blurb: 'Okamžik, který přestal být pomíjivý.',
    requires: { all: ['chemistry', 'optics'] },
    cost: 5,
    affinity: { curiosity: 0.8 },
    unlocks: { research: 1.15 },
    fragility: 0.5,
  },

  // ───────────────────────────── Epocha 9 — Elektřina a atom
  {
    id: 'power_grid',
    name: 'Rozvodná síť',
    epoch: 9,
    blurb: 'Energie dostupná všude, kde je zásuvka.',
    requires: { all: ['electric_generator'], any: ['telegraph', 'factory'] },
    cost: 7,
    affinity: { crowding: 0.6, cold: 0.4 },
    unlocks: { capacity: 1.6, research: 1.5, specialization: 0.1 },
    fragility: 0.7,
  },
  {
    id: 'radio',
    name: 'Rádio',
    epoch: 9,
    blurb: 'Zpráva bez drátu, bez posla, bez hranic.',
    requires: { all: ['telegraph'], any: ['power_grid', 'thermodynamics'] },
    cost: 6,
    costMods: [
      { why: 'dráždivá hvězda ruší každé vysílání', planet: { key: 'magneticField', below: 0.25 }, mul: 2.5 },
    ],
    affinity: { crowding: 0.5, war: 0.4, curiosity: 0.5 },
    unlocks: { research: 1.4 },
    fragility: 0.7,
  },
  {
    id: 'antibiotics',
    name: 'Antibiotika',
    epoch: 9,
    blurb: 'Plíseň, která zabíjí to, co zabíjelo nás.',
    requires: { all: ['germ_theory', 'chemistry'] },
    cost: 7,
    affinity: { disease: 1 },
    unlocks: { relief: { disease: 0.5 }, capacity: 1.4 },
    fragility: 0.6,
  },
  {
    id: 'relativity',
    name: 'Relativita',
    epoch: 9,
    blurb: 'Čas se ukázal být místní záležitostí.',
    requires: { all: ['calculus'], any: ['radio', 'telescope'] },
    cost: 8,
    affinity: { curiosity: 1 },
    unlocks: { research: 1.5 },
    fragility: 0.65,
  },
  {
    id: 'quantum',
    name: 'Kvantová teorie',
    epoch: 9,
    blurb: 'Svět v nejmenším měřítku se odmítl chovat rozumně.',
    requires: { all: ['relativity'], any: ['chemistry', 'optics'] },
    cost: 9,
    affinity: { curiosity: 1 },
    unlocks: { research: 1.6 },
    fragility: 0.7,
  },
  {
    id: 'flight',
    name: 'Let',
    epoch: 9,
    blurb: 'Konečně nahoru.',
    requires: { all: ['precision_machining'], any: ['internal_combustion', 'electric_generator'] },
    cost: 8,
    costMods: [
      { why: 'těžká gravitace drží u země', planet: { key: 'gravity', above: 1.3 }, mul: 4 },
      { why: 'lehký svět s hustým vzduchem', planet: { key: 'gravity', below: 0.8 }, mul: 0.5 },
      { why: 'hustý vzduch nese křídla sám', planet: { key: 'atmosphereDensity', above: 1.5 }, mul: 0.6 },
    ],
    affinity: { war: 0.6, curiosity: 0.8, crowding: 0.3 },
    unlocks: { might: 0.6, research: 1.2, capacity: 1.15 },
    fragility: 0.65,
  },
  {
    id: 'nuclear_fission',
    name: 'Štěpení jádra',
    epoch: 9,
    blurb: 'Z jednoho gramu tolik energie, kolik z vagonu uhlí.',
    requires: { all: ['quantum'] },
    needsResources: ['uranium'],
    cost: 9,
    costMods: [{ why: 'uran se tu téměř nevyskytuje', ore: { id: 'uranium', below: 0.3 }, mul: 6 }],
    affinity: { curiosity: 0.9, war: 0.5 },
    unlocks: { research: 1.3 },
    fragility: 0.75,
  },
  {
    id: 'nuclear_power',
    name: 'Jaderná energetika',
    epoch: 9,
    blurb: 'Elektrárna, která se nemusí přikládat celé roky.',
    requires: { all: ['nuclear_fission', 'power_grid'] },
    cost: 7,
    affinity: { crowding: 0.5, cold: 0.3 },
    unlocks: { capacity: 1.6, research: 1.25 },
    fragility: 0.7,
  },
  {
    id: 'nuclear_weapons',
    name: 'Jaderná zbraň',
    epoch: 9,
    blurb: 'Poprvé si civilizace může ublížit rychleji, než se stačí rozmyslet.',
    requires: { all: ['nuclear_fission'], any: ['flight', 'rocketry'] },
    cost: 7,
    affinity: { war: 1 },
    unlocks: { might: 3 },
    fragility: 0.6,
  },
  {
    id: 'rocketry',
    name: 'Raketa',
    epoch: 9,
    blurb: 'Jediný stroj, který nepotřebuje, aby se měl od čeho odrazit.',
    requires: { all: ['chemistry'], any: ['flight', 'thermodynamics'] },
    cost: 8,
    costMods: [
      { why: 'z těžké planety se startuje bolestně', planet: { key: 'gravity', above: 1.3 }, mul: 3.5 },
      { why: 'nízká gravitace odpouští', planet: { key: 'gravity', below: 0.8 }, mul: 0.55 },
    ],
    affinity: { war: 0.6, curiosity: 0.8 },
    unlocks: { might: 0.6, research: 1.2 },
    fragility: 0.7,
  },
  {
    id: 'plastics',
    name: 'Plasty',
    epoch: 9,
    blurb: 'Materiál, který je levnější než cokoli, co roste.',
    requires: { all: ['chemistry'], any: ['internal_combustion', 'factory'] },
    needsResources: ['oil'],
    cost: 6,
    affinity: { crowding: 0.4 },
    unlocks: { capacity: 1.3, specialization: 0.1 },
    fragility: 0.6,
  },
  {
    id: 'mass_media',
    name: 'Hromadné sdělovací prostředky',
    epoch: 9,
    blurb: 'Milion lidí se poprvé dozví totéž ve stejnou chvíli.',
    requires: { all: ['radio'], any: ['photography', 'printing_press'] },
    cost: 6,
    affinity: { crowding: 0.6, war: 0.4 },
    unlocks: { research: 1.25, literacy: 0.1 },
    fragility: 0.7,
  },

  // ───────────────────────────── Epocha 10 — Informace
  {
    id: 'relay_computer',
    name: 'Reléový počítač',
    epoch: 10,
    blurb: 'Skříň plná cvakajících spínačů, která počítá rychleji než sto lidí.',
    requires: { all: ['power_grid', 'precision_machining'] },
    cost: 7,
    costMods: [
      { why: 'bez vzácných zemin zbývá jen mechanika', ore: { id: 'rare', below: 0.3 }, mul: 0.5 },
    ],
    affinity: { curiosity: 0.8, war: 0.4 },
    unlocks: { research: 1.4, specialization: 0.1 },
    fragility: 0.6,
  },
  {
    id: 'transistor',
    name: 'Tranzistor',
    epoch: 10,
    blurb: 'Spínač bez jediné pohyblivé části.',
    requires: { all: ['quantum'] },
    needsResources: ['rare'],
    cost: 8,
    costMods: [{ why: 'vzácné zeminy tu prakticky nejsou', ore: { id: 'rare', below: 0.3 }, mul: 5 }],
    affinity: { curiosity: 0.9 },
    unlocks: { research: 1.6, specialization: 0.1 },
    fragility: 0.8,
  },
  {
    id: 'computer',
    name: 'Počítač',
    epoch: 10,
    blurb: 'Stroj, který dělá to, co mu právě řekneš — a nic jiného.',
    requires: { any: ['transistor', 'relay_computer'] },
    cost: 8,
    affinity: { curiosity: 1, crowding: 0.3 },
    unlocks: { research: 1.9, specialization: 0.15 },
    fragility: 0.8,
  },
  {
    id: 'laser',
    name: 'Laser',
    epoch: 10,
    blurb: 'Světlo srovnané do jediného kroku.',
    requires: { all: ['quantum', 'optics'] },
    cost: 7,
    affinity: { curiosity: 0.9, war: 0.3 },
    unlocks: { research: 1.3, might: 0.3 },
    fragility: 0.75,
  },
  {
    id: 'integrated_circuit',
    name: 'Integrovaný obvod',
    epoch: 10,
    blurb: 'Milion spínačů na ploše nehtu.',
    requires: { all: ['transistor'], any: ['laser', 'precision_machining'] },
    cost: 8,
    affinity: { curiosity: 0.9 },
    unlocks: { research: 1.8, specialization: 0.1 },
    fragility: 0.85,
  },
  {
    id: 'satellite',
    name: 'Družice',
    epoch: 10,
    blurb: 'Oko, které nikdy nemrká.',
    requires: { all: ['rocketry'], any: ['radio', 'computer'] },
    cost: 7,
    affinity: { war: 0.5, curiosity: 0.7 },
    unlocks: { research: 1.3, might: 0.3 },
    fragility: 0.8,
  },
  {
    id: 'space_flight',
    name: 'Kosmický let',
    epoch: 10,
    blurb: 'Někdo se poprvé podíval na svůj svět zvenčí.',
    requires: { all: ['satellite'], any: ['computer', 'relay_computer'] },
    cost: 9,
    costMods: [{ why: 'těžká planeta si vybírá daň', planet: { key: 'gravity', above: 1.3 }, mul: 3 }],
    affinity: { curiosity: 1, war: 0.3 },
    unlocks: { research: 1.35 },
    fragility: 0.8,
  },
  {
    id: 'genetics',
    name: 'Genetika',
    epoch: 10,
    blurb: 'Návod, podle kterého se staví všechno živé.',
    requires: { all: ['antibiotics'], any: ['computer', 'optics'] },
    cost: 8,
    affinity: { disease: 0.9, curiosity: 0.8 },
    unlocks: { relief: { disease: 0.2 }, research: 1.4 },
    fragility: 0.75,
  },
  {
    id: 'green_revolution',
    name: 'Zelená revoluce',
    epoch: 10,
    blurb: 'Hlad přestal být přírodní silou a stal se otázkou rozdělování.',
    requires: { all: ['fertilizer'], any: ['genetics', 'crop_science'] },
    cost: 7,
    affinity: { hunger: 1 },
    unlocks: { capacity: 1.8, relief: { hunger: 0.4 } },
    fragility: 0.6,
  },
  {
    id: 'climate_science',
    name: 'Klimatologie',
    epoch: 10,
    blurb: 'Zjištění, že atmosféra si pamatuje všechno, co jsme do ní pustili.',
    requires: { all: ['computer'], any: ['satellite', 'chemistry'] },
    cost: 6,
    affinity: { curiosity: 0.8, hunger: 0.3 },
    unlocks: { research: 1.2 },
    fragility: 0.75,
  },
  {
    id: 'network',
    name: 'Datová síť',
    epoch: 10,
    blurb: 'Počítače, které si povídají mezi sebou.',
    requires: { all: ['computer'], any: ['satellite', 'power_grid'] },
    cost: 8,
    affinity: { curiosity: 0.9, crowding: 0.4 },
    unlocks: { research: 1.7, specialization: 0.1 },
    fragility: 0.85,
  },

  // ───────────────────────────── Epocha 11 — Sítě a biotechnologie
  {
    id: 'internet',
    name: 'Internet',
    epoch: 11,
    blurb: 'Všechno vědění na dosah a nikdo neví, co je pravda.',
    requires: { all: ['network'], any: ['integrated_circuit', 'computer'] },
    cost: 8,
    affinity: { curiosity: 1, crowding: 0.5 },
    unlocks: { research: 2, literacy: 0.2 },
    fragility: 0.9,
  },
  {
    id: 'genome',
    name: 'Přečtený genom',
    epoch: 11,
    blurb: 'Celý návod přepsaný do písmen, kterým zatím nerozumíme.',
    requires: { all: ['genetics'], any: ['computer', 'integrated_circuit'] },
    cost: 7,
    affinity: { disease: 0.8, curiosity: 0.8 },
    unlocks: { research: 1.4, relief: { disease: 0.15 } },
    fragility: 0.85,
  },
  {
    id: 'gene_editing',
    name: 'Editace genů',
    epoch: 11,
    blurb: 'Nůžky, které stříhají to, co dřív určovala jen náhoda.',
    requires: { all: ['genome'] },
    cost: 8,
    affinity: { disease: 1, hunger: 0.4 },
    unlocks: { relief: { disease: 0.4 }, capacity: 1.5, research: 1.3 },
    fragility: 0.85,
  },
  {
    id: 'renewable_grid',
    name: 'Obnovitelná síť',
    epoch: 11,
    blurb: 'Energie ze slunce a větru, konečně levnější než ta z ohně.',
    requires: { all: ['power_grid'], any: ['integrated_circuit', 'climate_science', 'geothermal'] },
    cost: 7,
    affinity: { crowding: 0.5, cold: 0.3 },
    unlocks: { capacity: 1.6, research: 1.2 },
    fragility: 0.8,
  },
  {
    id: 'fusion',
    name: 'Termojaderná fúze',
    epoch: 11,
    blurb: 'Hvězda uzavřená v nádobě, konečně o něco déle než na okamžik.',
    requires: { all: ['laser'], any: ['nuclear_power', 'quantum'] },
    cost: 10,
    affinity: { crowding: 0.5, curiosity: 0.8 },
    unlocks: { capacity: 1.5, research: 1.5 },
    fragility: 0.85,
  },
  {
    id: 'machine_learning',
    name: 'Strojové učení',
    epoch: 11,
    blurb: 'Program, který nikdo nenapsal — jen ukázal, co má vyjít.',
    requires: { all: ['internet'], any: ['integrated_circuit', 'computer'] },
    cost: 8,
    affinity: { curiosity: 1 },
    unlocks: { research: 1.9, specialization: 0.15 },
    fragility: 0.9,
  },
  {
    id: 'longevity',
    name: 'Prodloužení života',
    epoch: 11,
    blurb: 'Stárnutí přeřazeno mezi nemoci.',
    requires: { all: ['gene_editing'], any: ['machine_learning', 'genome'] },
    cost: 9,
    affinity: { disease: 0.9, crowding: 0.4 },
    unlocks: { capacity: 1.4, relief: { disease: 0.3 }, research: 1.2 },
    fragility: 0.9,
  },
  {
    id: 'orbital_industry',
    name: 'Orbitální průmysl',
    epoch: 11,
    blurb: 'Továrny tam, kde nevadí, že nemají kam vypustit odpad.',
    requires: { all: ['space_flight'], any: ['fusion', 'machine_learning', 'assembly_line'] },
    cost: 9,
    costMods: [{ why: 'z lehké planety se vynáší snadno', planet: { key: 'gravity', below: 0.8 }, mul: 0.5 }],
    affinity: { crowding: 0.6, curiosity: 0.7 },
    unlocks: { capacity: 1.5, research: 1.3 },
    fragility: 0.9,
  },
  {
    id: 'nanotech',
    name: 'Nanotechnologie',
    epoch: 11,
    blurb: 'Stavění po jednotlivých atomech.',
    requires: { all: ['machine_learning'], any: ['gene_editing', 'laser'] },
    cost: 9,
    affinity: { curiosity: 0.9, disease: 0.3 },
    unlocks: { research: 1.5, capacity: 1.3 },
    fragility: 0.9,
  },
  {
    id: 'climate_engineering',
    name: 'Klimatické inženýrství',
    epoch: 11,
    blurb: 'Zásah do počasí celé planety. Co může být špatně.',
    requires: { all: ['climate_science'], any: ['fusion', 'renewable_grid', 'nanotech'] },
    cost: 8,
    affinity: { hunger: 0.7, cold: 0.6, crowding: 0.4 },
    unlocks: { capacity: 1.5, relief: { cold: 0.3, hunger: 0.2 } },
    fragility: 0.85,
  },
  {
    id: 'global_governance',
    name: 'Světová správa',
    epoch: 11,
    blurb: 'Konečně jedno místo, kde se dá dohodnout to, co se týká všech.',
    requires: { all: ['internet'], any: ['constitution', 'global_trade'] },
    cost: 8,
    affinity: { war: 1, crowding: 0.5 },
    unlocks: { relief: { war: 0.4 }, research: 1.25, specialization: 0.1 },
    fragility: 0.9,
  },

  // ───────────────────────────── Epocha 12 — Postlidská éra
  {
    id: 'agi',
    name: 'Obecná umělá inteligence',
    epoch: 12,
    blurb: 'Poprvé není nejchytřejší věcí na planetě nikdo z nich.',
    requires: { all: ['machine_learning'], any: ['integrated_circuit', 'nanotech'] },
    cost: 10,
    affinity: { curiosity: 1 },
    unlocks: { research: 2.5, specialization: 0.2 },
    fragility: 0.95,
  },
  {
    id: 'self_replication',
    name: 'Sebereplikující se výroba',
    epoch: 12,
    blurb: 'Stroj, který postaví stroj, který postaví stroj.',
    requires: { all: ['nanotech'], any: ['agi', 'orbital_industry'] },
    cost: 10,
    affinity: { crowding: 0.5, hunger: 0.5 },
    unlocks: { capacity: 1.7, research: 1.5 },
    fragility: 0.95,
  },
  {
    id: 'post_scarcity',
    name: 'Konec nedostatku',
    epoch: 12,
    blurb: 'Ekonomie se stala historickou disciplínou.',
    requires: { all: ['self_replication'], any: ['fusion', 'renewable_grid'] },
    cost: 10,
    affinity: { hunger: 1, crowding: 0.6, war: 0.5 },
    unlocks: { capacity: 1.6, relief: { hunger: 0.6, war: 0.3 }, research: 1.4 },
    fragility: 0.95,
  },
  {
    id: 'mind_uploading',
    name: 'Přenos vědomí',
    epoch: 12,
    blurb: 'Otázka, jestli ten na druhé straně je pořád ten samý, zůstala nezodpovězena.',
    requires: { all: ['agi'], any: ['genome', 'nanotech'] },
    cost: 11,
    affinity: { disease: 0.8, curiosity: 1 },
    unlocks: { research: 1.8, relief: { disease: 0.4 } },
    fragility: 0.95,
  },
  {
    id: 'space_habitat',
    name: 'Vesmírné habitaty',
    epoch: 12,
    blurb: 'Domov, který si nesou s sebou.',
    requires: { all: ['orbital_industry'], any: ['self_replication', 'post_scarcity'] },
    cost: 10,
    affinity: { crowding: 1 },
    unlocks: { capacity: 1.8, relief: { crowding: 0.4 } },
    fragility: 0.95,
  },
  {
    id: 'terraforming',
    name: 'Terraformace',
    epoch: 12,
    blurb: 'Planeta předělaná podle toho, co se komu hodí.',
    requires: { all: ['climate_engineering'], any: ['space_habitat', 'self_replication'] },
    cost: 11,
    affinity: { crowding: 0.7, hunger: 0.5, cold: 0.5 },
    unlocks: { capacity: 1.6, relief: { cold: 0.5, hunger: 0.3 } },
    fragility: 0.95,
  },
  {
    id: 'synthetic_biosphere',
    name: 'Syntetická biosféra',
    epoch: 12,
    blurb: 'Život navržený od nuly, bez ohledu na to, co se vyvinulo samo.',
    requires: { all: ['nanotech'], any: ['gene_editing', 'terraforming'] },
    cost: 10,
    affinity: { hunger: 0.8, disease: 0.5 },
    unlocks: { capacity: 1.5, relief: { hunger: 0.4 } },
    fragility: 0.95,
  },
  {
    id: 'interstellar_probe',
    name: 'Mezihvězdná sonda',
    epoch: 12,
    blurb: 'Poslali něco tam, kam nikdo z nich nedohlédne.',
    requires: { all: ['fusion'], any: ['space_habitat', 'self_replication'] },
    cost: 11,
    affinity: { curiosity: 1 },
    unlocks: { research: 1.5 },
    fragility: 0.95,
  },
  {
    id: 'consciousness_theory',
    name: 'Teorie vědomí',
    epoch: 12,
    blurb: 'Nejstarší otázka konečně zodpovězena. Odpověď se nikomu nelíbila.',
    requires: { all: ['mind_uploading'], any: ['agi', 'genome'] },
    cost: 11,
    affinity: { curiosity: 1 },
    unlocks: { research: 2 },
    fragility: 0.95,
  },
  {
    id: 'dyson_swarm',
    name: 'Dysonův roj',
    epoch: 12,
    blurb: 'Hvězda obestavěná tak, aby z ní nic neuniklo nevyužité.',
    requires: { all: ['space_habitat', 'self_replication'] },
    cost: 12,
    affinity: { crowding: 0.8, curiosity: 0.8 },
    unlocks: { capacity: 2, research: 2 },
    fragility: 0.95,
  },

  // ───────────────────────────── Epocha 13 — Transcendence
  {
    id: 'substrate_independence',
    name: 'Nezávislost na substrátu',
    epoch: 13,
    blurb: 'Přestalo záležet na tom, z čeho jsou.',
    requires: { all: ['mind_uploading'], any: ['consciousness_theory', 'dyson_swarm'] },
    cost: 10,
    affinity: { curiosity: 1 },
    unlocks: { research: 2, relief: { disease: 0.6 } },
    fragility: 0.98,
  },
  {
    id: 'stellar_engineering',
    name: 'Hvězdné inženýrství',
    epoch: 13,
    blurb: 'Hvězda přeladěná tak, aby vydržela déle, než měla.',
    requires: { all: ['dyson_swarm'] },
    cost: 12,
    affinity: { curiosity: 0.9, crowding: 0.5 },
    unlocks: { capacity: 1.6, research: 1.8 },
    fragility: 0.98,
  },
  {
    id: 'deep_time_planning',
    name: 'Plánování v hlubokém čase',
    epoch: 13,
    blurb: 'Rozhodnutí, jejichž následky nastanou za milion let, a přesto se dělají pečlivě.',
    requires: { all: ['substrate_independence'] },
    cost: 11,
    affinity: { curiosity: 1 },
    unlocks: { research: 2 },
    fragility: 0.98,
  },
  {
    id: 'matter_programming',
    name: 'Programovatelná hmota',
    epoch: 13,
    blurb: 'Rozdíl mezi věcí a jejím popisem přestal být podstatný.',
    requires: { all: ['self_replication'], any: ['substrate_independence', 'stellar_engineering'] },
    cost: 12,
    affinity: { crowding: 0.6, hunger: 0.5 },
    unlocks: { capacity: 1.8, research: 1.8 },
    fragility: 0.98,
  },
  {
    id: 'galactic_reach',
    name: 'Galaktický dosah',
    epoch: 13,
    blurb: 'Už to není civilizace planety.',
    requires: { all: ['interstellar_probe'], any: ['stellar_engineering', 'matter_programming'] },
    cost: 13,
    affinity: { curiosity: 1, crowding: 0.7 },
    unlocks: { capacity: 2, research: 2 },
    fragility: 0.98,
  },
  {
    id: 'physics_completion',
    name: 'Uzavření fyziky',
    epoch: 13,
    blurb: 'Poslední rovnice dopsána. Ukázalo se, že to nebyl konec, ale předmluva.',
    requires: { all: ['deep_time_planning'], any: ['galactic_reach', 'matter_programming'] },
    cost: 13,
    affinity: { curiosity: 1 },
    unlocks: { research: 2.5 },
    fragility: 0.98,
  },
  {
    id: 'the_quiet_question',
    name: 'Tichá otázka',
    epoch: 13,
    blurb: 'Když je možné všechno, zbývá jediná otázka — a na tu jim nikdo neodpoví.',
    requires: { all: ['physics_completion'] },
    cost: 14,
    affinity: { curiosity: 1 },
    unlocks: { research: 1.5 },
    fragility: 0.98,
  },
];
